trigger:
  branches:
    include:
      - main
  batch: 'true'

pool:
  default


steps:
- task: NodeTool@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Installing dependencies'

- script: |
    npm run build
  displayName: 'Building project'

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'webApp'
    appName: markaryd-frontned-development
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'